# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# SQL Server (SQLEXPRESS)
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=saas_project_manager;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Using Windows Authentication
spring.datasource.username=saas_user
spring.datasource.password=StrongPassword@123

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=projectmanager

jwt.secret=MySuperSecretKeyForJwtThatIsVerySecureAndLong
jwt.expiration=86400000

